app.py
from flask.templating import render_template
from flask import Flask
from views.extract_item import extract_item_blueprint
from views.get_revision_rules import get_revision_rules_blueprint
from views.get_part_material import get_part_material_blueprint

app = Flask(__name__)

app.register_blueprint(extract_item_blueprint, url_prefix="/item_extract")
app.register_blueprint(get_revision_rules_blueprint, url_prefix="/get_revision_rules")
app.register_blueprint(get_part_material_blueprint, url_prefix="/get_material_info")


@app.route("/")
def hello():
    return render_template("index.html")


if __name__ == '__main__':
    app.run(debug=True)

views/extract_item.py
import json
from flask import jsonify, Blueprint, json
from flask.globals import request
from flask.templating import render_template
from modules import extract_item_properties


extract_item_blueprint = Blueprint('extract', __name__)

#route for the browser 
@extract_item_blueprint.route('/', methods=["GET", "POST"])
def new_item():
    item_dict = {}
    if request.method == 'POST':
        item_id = request.form['item_id']
        rev_id = request.form['rev_id']

        item_dict = extract_item_properties.extract_item_properties(
            item_id, rev_id)

    return render_template('item_extraction.html', item_dict=item_dict)

#route for the REST Application
@extract_item_blueprint.route("/rest", methods=["POST"])
def extract_item_rest():
    datadict = request.get_json()
    item_id = datadict['item_id']
    rev_id = datadict['rev_id']
    outputlist = extract_item_properties.extract_item_properties(
        item_id, rev_id)
    retJson = outputlist
    return jsonify(retJson)

views/get_part_material.py
from flask import jsonify, Blueprint
from flask.globals import request
from flask.templating import render_template
from modules import get_part_material


get_part_material_blueprint = Blueprint('get_part_material', __name__)

#route for the browser 
@get_part_material_blueprint.route('/', methods=["GET", "POST"])
def get_part_material_view():
    item_dict = {}
    if request.method == 'POST':
        item_id = request.form['item_id']
        rev_id = request.form['rev_id']
        dic_collection = get_part_material.execute_as_obj(item_id, rev_id)
        print('Result dic:', str(item_dict))
    return render_template('get_part_material.html', dics=dic_collection)

#route for the REST Application
@get_part_material_blueprint.route("/rest", methods=["POST"])
def extract_item_rest():
    datadict = request.get_json()
    item_id = datadict['item_id']
    rev_id = datadict['rev_id']
    outputlist = get_part_material.execute_as_json(item_id, rev_id)
    retJson = outputlist
    return jsonify(retJson)

views/get_revision_rules.py
from flask import Blueprint, Response
from flask.templating import render_template
from modules import get_revision_rules

get_revision_rules_blueprint = Blueprint('get_revision_rules', __name__)

@get_revision_rules_blueprint.route("/", methods=["GET"])
def get_revision_rules_view():
    response_dics = get_revision_rules.execute_as_obj()
    return render_template('revision_rules.html', rule_dics=response_dics)

@get_revision_rules_blueprint.route("/json", methods=["GET"])
def get_revision_rules_json_view():
    response = get_revision_rules.execute_as_json()
    return Response(response, mimetype='text/json')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>RePyTI</title>
</head>
<body>
    <div class= "content container">
        <h1>RePyTI</h1>
        {% block content %}
        
        {% endblock %}
    </div>
</body>
</html>

templates/get_part_material.html
{% extends "base.html" %}

{% block content %}

<header><h1>Related Material Information</h1></header>
<section class="extract-item-form">
    <form method="POST">
        <div class="mb-3">
            <label for="item_id">Item_ID</label>
            <input type="text" class="form-control" id="item_id" name="item_id" placeholder="Example: 048417" />
        </div>
        <div class="mb-3">
            <label for="rev_id">Revision ID</label>
            <input type="text" class="form-control" id="rev_id" name="rev_id" placeholder="Example: 00" />
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</section>

<h2>Material Info</h2>
<section>
    {% for dic in dics %}
    <div class="list-group">
        {% for key, value in dic.items() %}
            <div class="list-group-item">
                <p style="font-weight: bold;">{{key}}</p>
                <p>
                    <p>{{value}}</p>
                </p>
            </div>
        {% endfor %}
    </div>
    {% endfor %}
</section>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

<header><h1>Modules: </h1></header>
<ul>
    <li><a href={{ url_for('extract.new_item') }}> Extract Item Information</a></li>
    <li><a href={{ url_for('get_revision_rules.get_revision_rules_view') }}>Get Revision Rules</a></li>
    <li><a href={{ url_for('get_part_material.get_part_material_view') }}>Get Material Iformation of Part</a></li>
</ul>   

{% endblock %}

templates/item_extraction.html
{% extends "base.html" %}

{% block content %}

<header><h1>Extract Item Information</h1></header>
<section class="extract-item-form">
    <form method="POST">
        <div class="mb-3">
            <label for="item_id">Item_ID</label>
            <input type="text" class="form-control" id="item_id" name="item_id" placeholder="Example: 048417" />
        </div>
        <div class="mb-3">
            <label for="rev_id">Revision ID</label>
            <input type="text" class="form-control" id="rev_id" name="rev_id" placeholder="Example: 00" />
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</section>

<h2>Item Info</h2>
<section>
    <div class="list-group">
        {% for key, value in item_dict.items() %}
            <div class="list-group-item">
                <p style="font-weight: bold;">{{key}}</p>
                <p>
                    <p>{{value}}</p>
                </p>
            </div>
        {% endfor %}
    </div>
</section>

{% endblock %}

templates/revision_rules.html
{% extends "base.html" %}

{% block content %}

<header><h1>Revision Rules Information</h1></header>
<section>
    {% for dic in rule_dics %}
            <div class="list-group">
                {% for key, value in dic.items() %}
                    <div class="list-group-item">
                        <p>
                            <span style="font-weight: bold;">{{key}}</span>: {{value}}
                        </p>
                    </div>
                {% endfor %}
            </div>
            <hr />
    {% endfor %}
</section>

{% endblock %}